### PR TITLE
feat: drag card with mouse offset

### PR DESCRIPTION
**Pull request by nathanosoares**
This feature hold the relative offset mouse position

### CODE REVIEW

**Comment by nathanosoares** [comment]
let's test before the merge :p

https://asuma-git-fork-nathanosoares-feat-drag-mouse-offset-tigerabrodi.vercel.app/

**Comment by nathanosoares** [comment]
now the drag it's fine

**Comment by tigerabrodi** [comment]
@nathanosoares sorry for being late, been busy, let me check it out, many thanks! :heart: :pray:

**Review by tigerabrodi — APPROVED** [review]
Astonishing, great work, much appreciated!

**Comment by tigerabrodi** [comment]
@nathanosoares Awesome, really appreciate this!! :pray: 

One last thing if you'd like to hack on it is being able to resize the cards.

Feel free to open an issue and hack on it if you're interested. :smile:

**Pull request merged**
