### PR TITLE
fix: adding movement offset to prevent position set to center

### PR DESCRIPTION
**Pull request by nathansoareskabum**
Adding offset to prevent card position reseting to mouse position on start drag movement

### CODE REVIEW

**Comment by nathanosoares** [comment]
I created this pull request with the wrong account :p

**Comment by tigerabrodi** [comment]
@nathanosoares Thanks for this! Taking a look right now :pray:

**Comment by tigerabrodi** [comment]
@nathanosoares 

There is a slight bug, hence I reverted it :grimacing: .

if you look, when not dragging around this happens by just moving the cursor...

https://user-images.githubusercontent.com/49603590/188894335-5d35e369-b694-4ccd-bdf8-5f24fea257b7.mp4

**Comment by nathanosoares** [comment]
I will try to solve this problem later today

**Pull request merged**
